name: Run Python Code

on:
  push:

jobs:
  run-code:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run Python script
        run: python main.py # 이곳에 실제 파이썬 파일명을 적어주세요.
